# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/xenial64"
  config.vm.box_version = "20211001.0.5"
  config.vm.network "private_network", ip: "10.0.0.10"

  config.vm.provider "virtualbox" do |vb| 
    vb.cpus = 1
    vb.memory = 1024
    vb.gui = true
  end

  config.vm.provision "ansible_local" do |ansible|
    ansible.playbook = "nginx.yml"
  end


end
